server:
  port: 8501
  tomcat:
    connection-timeout: 30000

# 配置数据库连接信息
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 8
      minimum-idle: 8
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      validation-timeout: 10000
      pool-name: manager-pool
      leak-detection-threshold: 20000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 4096
      initialization-fail-timeout: 1
      connection-init-sql: SELECT 1

  # Redis的相关配置
  data:
    redis:
      host: localhost
      port: 6379
  mvc:
    servlet:
      load-on-startup: 1
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  main:
    lazy-initialization: false
    allow-bean-definition-overriding: true
#  password: 1234
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# application.properties
#  logging:
#    level:
#      com.zaxxer.hikari: DEBUG
#      org.springframework: DEBUG